name: MirrorChyan Uploading

# 触发条件：手动触发或版本发布后
on:
  workflow_dispatch:
  release:    
    types: [published]

jobs:
  mirrorchyan:
    runs-on: macos-latest

    steps:
      - id: uploading
        uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "*full.zip"
          mirrorchyan_rid: March7thAssistant

          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
