name: Update Submodule
on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Update Submodule
        run: |
          git submodule update --remote

      - name: Check for Submodule Changes
        id: submodule_changes
        run: |
          git diff --quiet || echo "Submodule changes detected" 
          
      - name: Trigger Main Repository Update
        if: steps.submodule_changes.outputs.submodule_changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update Auto_Simulated_Universe to latest commit"
          git push
