name: Update Submodule
on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"
permissions:
  contents: write
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Update Submodule
        run: |
          git submodule update --remote
          echo "SUBMODULE_CHANGED=$(git diff --quiet || echo \"true\")" >> $GITHUB_ENV
          
      - name: Trigger Main Repository Update
        if: ${{ env.SUBMODULE_CHANGED == 'true' }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Auto_Simulated_Universe to latest commit"
          git push
